version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n-service
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
      - ${DATA_FOLDER}/local_files:/files
    networks:
      - backend
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-atlas-local
    hostname: mongodb
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - n8n_db:/data/db
      - configdb:/data/configdb
      - mongot:/data/mongot
    networks:
      - backend

  crawl4ai:
    image: unclecode/crawl4ai:latest
    container_name: crawl4ai
    ports:
      - '11235:11235'
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - backend
    restart: always

  kokoro-fastapi-gpu:
    ports:
      - 8880:8880
    image: ghcr.io/remsky/kokoro-fastapi-gpu:v0.2.4
    restart: always
    deploy:
      resources:
        reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities:
                 - gpu

  whisper-asr-webservice:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: whisper-service
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
    ports:
      - 9000:9000
    volumes:
      - cache-whisper:/root/.cache
    networks:
      - backend
    restart: always
      
volumes:
  n8n_data:
    external: true
  n8n_db:
    external: true
  cache-whisper:
    external: true
  configdb:
    external: true
  mongot:
    external: true

networks:
  backend:
    driver: bridge